### ISSUE TITLE
Hedgehog won't travel 100% 

### ISSUE THREAD

**Issue by shelbyboyd** [shelbyboyd/dsn1676-term-project#2]
@thomasjbradley

I'm confused as the hedgehog only travels an inch instead of gliding 100% across the screen. I want him to float from the left to the right of the page.  
# hedgehog {

```
display: block;
overflow: hidden;
width: 6em;
-webkit-animation: walkaround 8s forwards;
animation: walkaround 8s forwards;
```

}

-webkit-@keyframes walkaround {
    0% {
        -webkit-transform: translateX(0%);
    }

```
100% {
    -webkit-transform: translateX(100%);
}
```

}

@keyframes walkaround {
    0% {
        transform: translateX(0%);
    }

```
100% {
    transform: translateX(100%);
}
```

}

**Comment by thomasjbradley** [comment]
That makes sense, because `translateX` is based on the element itself... so moving 100% means, "take the width of this element and move that far."

**Comment by shelbyboyd** [comment]
Oh, okay. That does make sense then.  

Thank you Thomas
